/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: User2005 (https://sketchfab.com/lorenzo.brewer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phone-5c53e579e1ec49d0a68a380316c252dc
Title: Phone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PhoneModel(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Matt_Black_Plastic}
        position={[0.448, 0.014, 0]}
        scale={12.08}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Silver}
        position={[0.448, 0.013, 0]}
        scale={[12.079, 36.237, 12.079]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Matt}
        position={[0.448, 0.013, 0]}
        scale={[12.079, 36.237, 12.079]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Rubber}
        position={[0.714, 1.729, -0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={17.14}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Phone_color}
        position={[0.714, 1.729, -0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={17.14}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.Glass}
        position={[0.714, 1.729, -0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={17.14}
      />
      <mesh
        geometry={nodes.Object_15.geometry}
        material={materials.Black_Screen}
        position={[0.714, 1.527, -0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={21.052}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.material}
        position={[0.553, 1.734, -0.061]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={16.362}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials["Material.004"]}
        position={[0.553, 1.496, -0.061]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[32.573, 16.362, 32.573]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Plastic_Glass}
        position={[0.553, 1.496, -0.061]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[32.573, 16.362, 32.573]}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.Phone_color}
        position={[0.277, 1.907, -0.006]}
        scale={[12.08, 12.08, 8.596]}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.Lems}
        position={[0.714, 1.729, -0.055]}
        scale={[0.017, 0.017, 0.012]}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
